### ISSUE TITLE
Asymptotic behavior

### ISSUE THREAD

**Issue by yossigil** [yossi-cohen/preferential-attachment#13]
Design an experiment to demonstrate or refute the conjecture that you can increase accuracy umindefitely? E, g, accuracy of 10e-12, 10e-20?

**Comment by yossi-cohen** [comment]
**STD < 1e-10**

![universal-estimator-exp-1c-e-10](https://user-images.githubusercontent.com/2950595/130203502-f598203c-2a4b-47b1-a3f9-a3c1477bb16a.png)

**STD < 1e-12**

![universal-estimator-exp-1c-e-12](https://user-images.githubusercontent.com/2950595/130203533-a19f8988-87c7-4b48-80f1-0ae839c1fee9.png)

**Comment by yossigil** [comment]
so, yes, the graphs demonstrate the bug. the average error decreases because you select data from a search space that is as small as the error...
