### ISSUE TITLE
Show we get results as expected by Cramér–Rao bound

### ISSUE THREAD

**Issue by yossi-cohen** [yossi-cohen/preferential-attachment#15]
- Generate N=1000 random samples (256 observations each) using  𝑓(𝑑)  with d ~ uniform(search_space)
- Fit a DNN model
- Predict the samples parameters using the model
  > `d_pred_array = model.predict(samples)`
  > `errors_d_pred = (d_pred_array - d_true_array)`
- Plot the distribution of `errors_d_pred`

**Results**:
(the x axis is actually d_pred - d_true and not the abs)

N = 1,000  
MAE: 0.0497  
STD: 0.0630  
![universal-estimator-exp-1c-N1000](https://user-images.githubusercontent.com/2950595/130311069-4d962e15-87ea-4e69-b909-816c0428c402.png)

N = 10,000  
MAE: 0.0445  
STD: 0.0562  
![universal-estimator-exp-1c-N10000](https://user-images.githubusercontent.com/2950595/130311078-4e0166ac-9ef8-4d85-b6cb-c84f3c8a00e6.png)

N = 100,000  
MAE: 0.0433  
STD: 0.0560  
![universal-estimator-exp-1c-N100000](https://user-images.githubusercontent.com/2950595/130311081-1a5424f5-0816-4451-ba5b-dd3e2ee41c76.png)

**Comment by yossigil** [comment]
These are superb results. They show that we are in the area of the theoretical bound of 0.08 for theta=0.92. STD = 0.056 is great. I do not worry about the little deviation from the bound.
