### ISSUE TITLE
Fix log scale diagrams

### ISSUE THREAD

**Issue by yossigil** [yossi-cohen/preferential-attachment#18]
In logarithmic diagrams, you draw the log of a value, but you do not write on the tick markers the value of the log, but the original value. 

For example, https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.WReHKSwxD-TKFveL7bUZ1gHaHA%26pid%3DApi&f=1

Also,

https://3.bp.blogspot.com/-9cdvkreESaw/U_xrpf2SjZI/AAAAAAAAAG0/mI8rI_63JNw/s1600/semilogx-plot-using-matlab.jpg

**Comment by yossigil** [comment]
See graphs in #16

**Comment by yossi-cohen** [comment]
I'm not sure I follow you: the tick markers on the Y axis of the right graph are in log scale.
See fix at the bottom of [issue #16](https://github.com/yossi-cohen/preferential-attachment/issues/16)
Did you ment to scale also the X axis?

**Comment by yossigil** [comment]
I could not find the fix. To clarify, if quantity Something ranges between 1 and 10^6, then the Y axis is 6 centimetres; with the following tick marks:

- No tik at distance = 0, this is where the Y axis crosses the X axis. 
- Tik 1 at distance = 0.5
- Tik 10 at distance = 2.5
- Tik 100 at distance = 3.5
- Tik 10,000 at distance = 4.5
- Tik 100,000 at distance = 5.5
- No tick at distance = 6
- Arrow above the tick 

Sub ticks should be at Something = 2, 5, 20, 50, ...

See the examples I referenced.

**Comment by yossi-cohen** [comment]
For [0.01, 1.0]:
![issue-16_0 01-1](https://user-images.githubusercontent.com/2950595/131461732-5f7e3682-16a1-4134-beb3-e412052ebc2a.png)

For [0.01, 0.3]:
![issue-16_0 01-0 3](https://user-images.githubusercontent.com/2950595/131461748-3f6732ae-cf43-4b7b-87c4-d83fb3323e10.png)

**Comment by yossigil** [comment]
Wow
