### ISSUE TITLE
Multiple scales on the Y axis

### ISSUE THREAD

**Issue by yossigil** [yossi-cohen/preferential-attachment#19]
The graph in the left is not readable, since you use the same scale for two distinct values, which range in different scales. The red and the blue curves should be seen on the same graph, but in different scales. 

![image](https://user-images.githubusercontent.com/12775400/130907691-ef090ad8-9a62-4bf9-87d2-f9807fd6064a.png)

Here are a few examples on how this should look like:

https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.xwIFzEzqijI0FY1l8ukrdAHaFZ%26pid%3DApi&f=1

https://stackoverflow.com/questions/42734109/two-or-more-graphs-in-one-plot-with-different-x-axis-and-y-axis-scales-in-pyth

No need to fix the graphs in #16; but once you redo these, or when you do more graphs, please keep up to these:

Also: 
https://3.bp.blogspot.com/-9cdvkreESaw/U_xrpf2SjZI/AAAAAAAAAG0/mI8rI_63JNw/s1600/semilogx-plot-using-matlab.jpg

This example demonstrates two things: how grid is used to highlight locations, and, how the axis in logarithmic scales bear the original values, not their log. 

The objective is to use the graph to demonstrate, prove or refute a conjecture. We need to be able sometimes to see values on the graphs, and the grid makes it easier to read these values.

Using the original values, rather than their log, is customary. It eliminates the need to do the exponent in your head, it removes the need to mention that this is a logarithmic graph.

**Comment by yossigil** [comment]
No need to fix existing graphs, but if we reference an existing graph again, this should be fixed before.

**Comment by yossi-cohen** [comment]
See fix at the bottom of [issue #16](https://github.com/yossi-cohen/preferential-attachment/issues/16)

**Comment by yossigil** [comment]
Indeed!
