### ISSUE TITLE
Grid on graphs

### ISSUE THREAD

**Issue by yossigil** [yossi-cohen/preferential-attachment#20]
To make the graphs more readable, it is advisable to place a grid. This makes it easier to see what happens in the interesting areas. 

https://www.includehelp.com/python/grid-to-the-plot.aspx

Again, not needed to go back and fix graphs in #16, but for every graph from now on, consider using a grid.

Check also this example: 

https://3.bp.blogspot.com/-9cdvkreESaw/U_xrpf2SjZI/AAAAAAAAAG0/mI8rI_63JNw/s1600/semilogx-plot-using-matlab.jpg

It shows how grid is used to highlight locations, and, how the axis in logarithmic scales bear the original values, not their log.

**Comment by yossigil** [comment]
Again, not needed to go back and fix all graphs, but for every graph from now on, consider using a grid.

**Comment by yossi-cohen** [comment]
See fix at the bottom of [issue #16](https://github.com/yossi-cohen/preferential-attachment/issues/16)
