### ISSUE TITLE
Log Experiment

### ISSUE THREAD

**Issue by yossigil** [yossi-cohen/preferential-attachment#3]
Run an experiment to *show* that using the log function improves something, either accuracy or learning rate, or both.
Use fixed setting, e.g, YS, samples = 256 or 512.
In this experiment use the LOG(1+X) function.

**Comment by yossigil** [comment]
Record conclusion that we can quote in a paper? Record graph/table?

**Comment by yossi-cohen** [comment]
**Experiment 1** - log vs. exact training (yule-simon)
**Conclusion**: using log function on the histogram input  does improve accuracy nor learning rate.

![yule-simon - log vs exact training](https://user-images.githubusercontent.com/2950595/125736431-225a74a8-679f-41cc-85c1-c2d2ab6a3a08.png)

**Comment by yossi-cohen** [comment]
**Experiment 1** - log vs. exact training (poisson)
**Conclusion**: (same as for yule-simon) using log function on the histogram input  does improve accuracy nor learning rate.

![poisson - log vs exact training](https://user-images.githubusercontent.com/2950595/125736978-00981fce-87f3-4f99-b98f-be1a03b1009f.png)

**Comment by yossigil** [comment]
:+1:
