### ISSUE TITLE
Log shift experiment

### ISSUE THREAD

**Issue by yossigil** [yossi-cohen/preferential-attachment#4]
Run an experiment to see which C is better if using the function LOG(1+C)
Try, e.g., C = 0.2, 0.5, 1, 2,

**Comment by yossigil** [comment]
Record the results, perhaps here, so we do not forget.

**Comment by yossi-cohen** [comment]
**Results:**
Values near 1 seams to be better (precision get worse is we increase C)

```
for M in [256, 512, 1024]

    X_train = generate_data_yulesimon ( N = 10,000, M = M )

    for C in ( 1 + [ 0.2, 0.5, 1.0, 2.0 ] )

        X_train = log_scale( X_train, C = C )
        ...
```

![yule-simon log-shift experiment](https://user-images.githubusercontent.com/2950595/125743771-76f8e7e3-dec7-4ee6-abd6-cfa17c16a857.png)

**Comment by yossigil** [comment]
Great
