### ISSUE TITLE
Possion experiment

### ISSUE THREAD

**Issue by yossigil** [yossi-cohen/preferential-attachment#5]
Learn Poisson in three different settings:

1. Use exact values.
2. Use Log.
3. Use P values, defined from the poisson thingy.

P(k) = Log(MEASURED(k) * k!)

**Comment by yossi-cohen** [comment]
**Experiment 1** - log vs. exact training (poisson)
**Conclusion**: using log function on the histogram input does seems to improve accuracy nor learning rate.
(log input is slightly better then exact input but it doesn't seem significant)

![poisson - log vs exact training](https://user-images.githubusercontent.com/2950595/125736978-00981fce-87f3-4f99-b98f-be1a03b1009f.png)

**Another run**

![poisson - log vs exact training (2)](https://user-images.githubusercontent.com/2950595/125741940-d7b48e8d-6013-4a3e-9c98-5c0db0b35072.png)

**Comment by yossigil** [comment]
:+1:
