### ISSUE TITLE
Bias experiment

### ISSUE THREAD

**Issue by yossigil** [yossi-cohen/preferential-attachment#6]
Same experiment as usual, but *make sure* the prediction is unbiased. Average difference should be close to zero

**Comment by yossigil** [comment]
This was not done, or did I miss something? I mean this is trivially true, but it should be recorded somehow, even experimented as sanity check?

**Comment by yossi-cohen** [comment]
It was done for **Yule-Simon**
Here are the results:
![yule-simon-bias](https://user-images.githubusercontent.com/2950595/125743385-9291ba71-83ed-48a4-856b-0050ee9480e6.png)

**Comment by yossigil** [comment]
:+1:
